### PR TITLE
Add glossary.md to docs

### LINKED ISSUE #5: RootViewController documentation
We need to add the definition of the RootViewController to our documentation. In doing so, we will also have to add the definition of a what is a UI Component.

### PR DESCRIPTION
**Pull request by csfar**
## Motivation
We should have a page in our documentation reserved to defining parts of
our framework.

## Modifications
I've created a file named glossary with the definition of a UI Component
and the definition of a RootViewController.

## Result
A new file in our docs folder has been added responsible for bein the
glossary of our documentation. Closes #5  

##  Checklist
 **This PR is**
* [x] In accordance with our coding principles.
* [x] Implementing tests wherever needed and possible.
* [x] Free of commented code.
* [x] Documented.
* [x] Closing an Issue or related to an Issue
* [x] Approved in the CI

### CODE REVIEW

**Review by VicFalcetta — DISMISSED** [review]
The text here inserted on the glossary is what it was agreed and discussed on our part of UI. I think there is no changes required from my part.

**Review by Galdineris — CHANGES_REQUESTED** [review]
Great Idea!
But could you add an index at the start and put the definitions in alphabetic order?
As a glossary, the definitions should be easy to find or navigate.

**Review by Galdineris — APPROVED** [review]
Thank you for the update!

**Review by VicFalcetta — APPROVED** [review]
Checked the addition of indexes and it didn't break any text format. Approved.

**Pull request merged**
