### PR TITLE
Tools

### LINKED ISSUE #15: Add SwiftLint to the project
In order to enforce a coding style, we need to add SwiftLint to our project. We should also make sure that it runs on our CI.
I don't know which labels to add to this Issue. I am thinking of creating a new one for this sort of work, called `repo`.

### PR DESCRIPTION
**Pull request by cassiaabarbosa**
## Motivation
Adding SwiftLint is a way to get clean code, one of our coding principles.
Closes #15 

## Modifications
- name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0

## Result
SwiftLint is available.

##  Checklist
 **This PR is**
* [x] In accordance with our coding principles.
* [x] Implementing tests wherever needed and possible.
* [x] Free of commented code.
* [x] Documented.
* [x] Closing an Issue or related to an Issue
* [x] Approved in the CI

### CODE REVIEW

**Review by csfar — APPROVED** [review]
👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by csfar** [comment]
We should get together to decide which rules to apply to our project.

**Comment by cassiaabarbosa** [comment]
Later, we cam disable them the code or in our swiftLint.yml

**Review by Galdineris — APPROVED** [review]
Well done @cassiaabarbosa !

**Pull request merged**
