### PR TITLE
Components Protocols

### LINKED ISSUE #9: Protocol for UI Components Data
FWComponent is the protocol implemented ideally by structs that will save data used to create UIComponents and data obtained on the form. This protocol can be implemented in case the user wants to create a custom struct.

### LINKED ISSUE #10: Form Data Structure
The FWForm is the form structure itself. It can be built from the data got from JSON in the form of attributes and FWCompontent #9 structs or directly created with that structures. This is the object passed to the RootViewContoller #4 to interpret and make the UI form.

### PR DESCRIPTION
**Pull request by Galdineris**
## Motivation
Form Data Structure is heavily reliant on components protocols and as such needed an implementation of the same

## Modifications
- Created FWComponent and FWSpecs protocols.

## Result
Other parts of the code should be able to interact with an abstract form of component and components now have a default implementation of their specifications.

##  Checklist
 **This PR is**
* [ ] In accordance with our coding principles.
* [ ] Implementing tests wherever needed and possible.
* [ ] Free of commented code.
* [ ] Documented.
* [ ] Closing an Issue or related to an Issue
* [ ] Approved in the CI

### CODE REVIEW

**Comment by Galdineris** [comment]
Default decoder implementation for FWComponents protocols are not finished yet. [String:Any] decodable conformance should be implemented (still being researched but [this](https://gist.github.com/mbuchetics/c9bc6c22033014aa0c550d3b4324411a) appear to be a definitive solution)

**Review by EdgSgroi — CHANGES_REQUESTED** [review]
In FW Component, the spacing between comments and attributes, in addition to the empty lines, make reading difficult. Please, considerate to use "///" to small texts instead "/** */" and try to keep all information about the same thing as close as possible.

**Review by EdgSgroi — COMMENTED** [review]
In FWComponent, is it really necessary use an extension to separate the custom init from the attributes? Isn't it adds some reading pollution? 

**ALREADY ANSWERED**

**Review by VicFalcetta — APPROVED** [review]
Seen the changes and what I need to adapt in the code. Since is not to master but to my branch I will approve so we can work.

**Pull request merged**
