### PR TITLE
Fix Documentation Generation on our CI

### LINKED ISSUE #14: Use Jazzy as a Action to create code documentation
The Jazzy framework, presented by Babo, is a great solution to document code in a quick way during the development while this documentations is automatically released in a static HTML page. Also is a good opportunity to learn how to make a single and consistent documentation.

Jazzy repo: https://github.com/realm/jazzy

This issue can only be resolved with the help of the following issue in SwiftPM Jazzy Docs: 
https://github.com/sersoft-gmbh/swifty-docs-action/issues/1

### PR DESCRIPTION
**Pull request by Galdineris**
## Motivation
Closes #14 
Our directory was confusing and classes presented ambiguous names.

## Modifications
- Renamed workflow files
- Renamed classes and files to less ambiguous names
- Removed previously generated docs folder
- Created new Update Documentation workflow
- Moved data structure files into their respective domain folders
- Moved all manual artefacts to new Resources folder

## Result
Our CI now generates documentation automatically when pushing to master.
Folder and files structure more clearly separated by domain.

##  Checklist
 **This PR is**
* [x] In accordance with our coding principles.
* [x] Implementing tests wherever needed and possible.
* [x] Free of commented code.
* [x] Documented.
* [x] Closing an Issue or related to an Issue
* [x] Approved in the CI

### CODE REVIEW

**Review by cassiaabarbosa — APPROVED** [review]
Well done!

**Review by EdgSgroi — CHANGES_REQUESTED** [review]
According to @VicFalcetta every structure named whit SingleLine should be renamed to PlainText.

**Comment by Galdineris** [comment]
@EdgSgroi @VicFalcetta 
I reverted the name to "singleLine" due to the UI components structure (Which used SingleLine nomenclature).
The change to "PlainText" also implied using the same object for both single line and multi line components (refactoring their operation).
Changing the name to PlainText without that could result in confusion between PlainText and MultiLine.

**Comment by EdgSgroi** [comment]
@Galdineris Let's discuss this better in a team meeting. Just because we aren't aligned.

**Review by EdgSgroi — APPROVED** [review]

**Pull request merged**
